// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.requirement.repository;

import com.requirement.repository.RequirementRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RequirementRepository_Roo_Jpa_Repository {
    
    declare @type: RequirementRepository: @Transactional(readOnly = true);
    
}
